const wordInputs = `cl1000
1 giihangdtzjavcaxnbtudpcnmzggbdabocpeplzercnctkcvhoujbrpbztjlpuymabumbppgrydkdzbadcsjdtpdftlusapza
3 6
4
1 fcsivbvhtzydbhhopdnlaisgqhlkizqhezglxocqgymjedw
2 24
3 10
3 11
1 bgqrvdnlmkjdbmishfpaazvujrkzctgfbizhhrrdgdtzxzysm
4
1 tixqvwpiufqrqhgldlpaizamxxuivbhlmubnqpalwdowlf
2 60
1 zsfbxajobmdztghgddnsmxfceaudttvjqqvehvpodkexaj
2 16
2 20
4
1 yqcpbiuggbcpohztsrdx
4
2 11
3 27
3 15
1 uzwawzavoeksdalsxtyovqucuhvgcuxgzgyqyonsktudnntsocamsivhumienopvxmwoaq
1 bniitwuu


1 ckxjkebrlngcjutizxrxeywsfkhnfligxzolwwozymjsatrbmjchghjezllrshwoasssmmstejwmztatydrjsaztkdyt`

module.exports= {
  wordInputs,
}